### ISSUE TITLE
Rawdog fails to run on initial install 

### ISSUE THREAD

**Issue by ssh-keyz** [AbanteAI/rawdog#12]
Ran `pip install rawdog-ai `
Ran `rawdog`

Received this error

`(base) ➜  ~ rawdog
Traceback (most recent call last):
  File "/Users/jesse/miniconda3/bin/rawdog", line 5, in <module>
    from rawdog.__main__ import main
  File "/Users/jesse/miniconda3/lib/python3.9/site-packages/rawdog/__main__.py", line 6, in <module>
    from rawdog.llm_client import LLMClient
  File "/Users/jesse/miniconda3/lib/python3.9/site-packages/rawdog/llm_client.py", line 8, in <module>
    from litellm import completion, completion_cost
  File "/Users/jesse/miniconda3/lib/python3.9/site-packages/litellm/__init__.py", line 6, in <module>
    from litellm.proxy._types import KeyManagementSystem
  File "/Users/jesse/miniconda3/lib/python3.9/site-packages/litellm/proxy/_types.py", line 78, in <module>
    class ModelInfo(LiteLLMBase):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 661, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/Users/jesse/miniconda3/lib/python3.9/typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class`

Looked over submitted issues and tried installing LLMClient and setup tools but they were already installed

**Comment by granawkins** [comment]
Hmm.. might be related to pydantic? I'm not using typing yet. You might try checking versions of litellm and pydantic?

**Comment by malibrated** [comment]
I have this issue too.  What version of pydantic should we be running? (I have 2.5.3)

**Comment by biobootloader** [comment]
@ssh-keyz are you still having this issue with the latest version?
