### ISSUE TITLE
Error when trying to use rawdog: "ModuleNotFoundError: No module named 'pkg_resources'"

### ISSUE THREAD

**Issue by JiHa-Kim** [AbanteAI/rawdog#19]
Hello. I have followed the instructions for installing, using `pip install rawdog-ai`:
However, when I prompt "rawdog" it gives me:
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python312\Scripts\rawdog.exe\__main__.py", line 4, in <module>
  File "C:\Python312\Lib\site-packages\rawdog\__main__.py", line 6, in <module>
    from rawdog.llm_client import LLMClient
  File "C:\Python312\Lib\site-packages\rawdog\llm_client.py", line 8, in <module>
    from litellm import completion, completion_cost
  File "C:\Python312\Lib\site-packages\litellm\__init__.py", line 518, in <module>
    from .utils import (
  File "C:\Python312\Lib\site-packages\litellm\utils.py", line 32, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by jiaweizhang1995** [comment]
`pip install setuptools` will fix it

**Comment by JiHa-Kim** [comment]
Thanks it worked, fixed it.
