### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by ProximaCA** [AbanteAI/rawdog#52]
randomrandomovic@MacBook-Pro-Random rawdog-main % rawdog
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/bin/rawdog", line 5, in <module>
    from rawdog.__main__ import main
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rawdog/__main__.py", line 9, in <module>
    from rawdog.llm_client import LLMClient
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/rawdog/llm_client.py", line 9, in <module>
    from litellm import completion, completion_cost
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/litellm/__init__.py", line 520, in <module>
    from .utils import (
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/litellm/utils.py", line 32, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
randomrandomovic@MacBook-Pro-Random rawdog-main % 

Python 3.12.1

**Comment by ProximaCA** [comment]
SOLUTION
pip install setuptools (possibly with sudo).
