### ISSUE TITLE
pyreadline3 is a dependency not installed

### ISSUE THREAD

**Issue by abhimanyupallavisudhir** [AbanteAI/rawdog#86]
Didn't work for me when I first installed it on Windows because it depends on the `readline` package -- this isn't available on Windows, but installing `pyreadline3` made it work for me. I guess it should be listed as a dependency for Windows machines?

**Comment by jakethekoenig** [comment]
Thanks for reporting! It's listed in the requirements.txt but that's actually not used by the pyrpoject.toml. I made a [pr](https://github.com/AbanteAI/rawdog/pull/88) that fixes the issue.

**Comment by rille111** [comment]
Got the same exception:
```bash
 ~❯  rawdog hello                                                                                                                                                                                                                                                       ❮  
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "B:\Packages\pyenv\pyenv-win\versions\3.12.3\Scripts\rawdog.exe\__main__.py", line 4, in <module>
  File "B:\Packages\pyenv\pyenv-win\versions\3.12.3\Lib\site-packages\rawdog\__main__.py", line 2, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'
```
, installed both pyreadline and pyreadline3 - didnt help.

Tried Python 3.12, 3.11, 3.10, 3.9, 3.8 all in virtual envs. Still no work. :/
